apiVersion: apps/v1
kind: Deployment
metadata:
  name: willem-assignment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: willem-assignment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: willem-assignment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: willem-assignment
    spec:
      # serviceAccountName: default
      # automountServiceAccountToken: true
      # enableServiceLinks: true
      containers:
        - name: willem-assignment
          image: registry.hub.docker.com/wgmouton/fyycops:latest
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3