apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: willem-assignment-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:                     
    - web
  routes:                          
  - kind: Rule
    match: Host(`fyy.assigments.wgmouton.com`)                       
    services:                      
    - kind: Service
      name: willem-assignment-service
      namespace: {{ .Release.Namespace }}
      passHostHeader: true
      port: 80                     
      scheme: http
  # tls:                             
  #   secretName: supersecret        
  #   options:                       
  #     name: opt                    
  #     namespace: default           
  #   certResolver: foo              
  #   domains:                       
  #   - main: fyy.assigments.wgmouton.com