apiVersion: v1
kind: Service
metadata:
  name: willem-assignment-service
spec:
  selector:
    app.kubernetes.io/name: willem-assignment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80